version: 0.0

os: linux

files:
  - source:  / # 현재 프로젝트의 루트 경로
    destination: /home/ec2-user/deploy/  # EC2 내부 배포 할 위치
    overwrite: yes # 덮어쓰기

hooks:
  ApplicationStart: # 배포가 끝나면 아래 명령어를 실행
     - location: scripts/deploy.sh
       timeout: 60

permissions:
  - object: /home/ec2-user/deploy/
    pattern: "**"
    owner: root
